insert into compannia (companniaNombre, companniaDescrp) values ('Thoughtsphere', 'Other injury of intrinsic muscle, fascia and tendon of right little finger at wrist and hand level');
insert into compannia (companniaNombre, companniaDescrp) values ('Oyoba', 'Sprain of joints and ligaments of other parts of neck, initial encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Youbridge', 'Poisoning by antirheumatics, not elsewhere classified, accidental (unintentional), initial encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Kwideo', 'Nondisplaced fracture of distal phalanx of left index finger, initial encounter for closed fracture');
insert into compannia (companniaNombre, companniaDescrp) values ('Skilith', 'Personal history of transient ischemic attack (TIA), and cerebral infarction without residual deficits');
insert into compannia (companniaNombre, companniaDescrp) values ('Pixoboo', 'Unspecified open wound of right lesser toe(s) with damage to nail');
insert into compannia (companniaNombre, companniaDescrp) values ('Twimm', 'Retiform parapsoriasis');
insert into compannia (companniaNombre, companniaDescrp) values ('Yodo', 'Pedestrian on foot injured in collision with pedal cycle in traffic accident');
insert into compannia (companniaNombre, companniaDescrp) values ('Agimba', 'Unspecified injury of flexor muscle, fascia and tendon of left index finger at wrist and hand level, initial encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Reallinks', 'Pedal cycle passenger injured in collision with car, pick-up truck or van in traffic accident, subsequent encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Livetube', 'Corrosion of first degree of abdominal wall, initial encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Livetube', 'Passenger of other special all-terrain or other off-road motor vehicle injured in traffic accident, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Voolia', 'Other paralytic syndrome following unspecified cerebrovascular disease affecting right non-dominant side');
insert into compannia (companniaNombre, companniaDescrp) values ('Tavu', 'Salter-Harris Type III physeal fracture of unspecified metatarsal, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Voolith', 'Nondisplaced fracture of body of hamate [unciform] bone, right wrist, subsequent encounter for fracture with routine healing');
insert into compannia (companniaNombre, companniaDescrp) values ('Dabjam', 'Burn of first degree of trunk, unspecified site, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Skippad', 'Displaced fracture of neck of unspecified radius, initial encounter for open fracture type I or II');
insert into compannia (companniaNombre, companniaDescrp) values ('Talane', 'Antepartum hemorrhage with coagulation defect, unspecified, second trimester');
insert into compannia (companniaNombre, companniaDescrp) values ('Wordtune', 'Driver of special construction vehicle injured in nontraffic accident, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Devbug', 'Pathological fracture in other disease, unspecified tibia and fibula, subsequent encounter for fracture with routine healing');
insert into compannia (companniaNombre, companniaDescrp) values ('Babbleblab', 'Puncture wound with foreign body, unspecified thigh, subsequent encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Chatterpoint', 'Toxic effect of corrosive acids and acid-like substances, undetermined, initial encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Brainbox', 'Other specified injury of intrinsic muscle, fascia and tendon of unspecified thumb at wrist and hand level, initial encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Brainlounge', 'Adverse effect of emollients, demulcents and protectants');
insert into compannia (companniaNombre, companniaDescrp) values ('Browsedrive', 'Displaced pilon fracture of left tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion');
insert into compannia (companniaNombre, companniaDescrp) values ('Yakijo', 'Nondisplaced segmental fracture of shaft of left femur');
insert into compannia (companniaNombre, companniaDescrp) values ('Flashset', 'Salter-Harris Type IV physeal fracture of unspecified metatarsal');
insert into compannia (companniaNombre, companniaDescrp) values ('Youfeed', 'Sprain of jaw, unspecified side');
insert into compannia (companniaNombre, companniaDescrp) values ('Yodel', 'Car passenger injured in collision with other type car in traffic accident, subsequent encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Jayo', 'Cervical spina bifida without hydrocephalus');
insert into compannia (companniaNombre, companniaDescrp) values ('Tambee', 'Infective myositis, unspecified site');
insert into compannia (companniaNombre, companniaDescrp) values ('Topdrive', 'Interstitial myositis, left ankle and foot');
insert into compannia (companniaNombre, companniaDescrp) values ('Zoozzy', 'Laceration of other urinary and pelvic organ, initial encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Meevee', 'Other specified injury of superficial vein at shoulder and upper arm level, left arm, subsequent encounter');
insert into compannia (companniaNombre, companniaDescrp) values ('Topicware', 'Strain of other muscle(s) and tendon(s) of posterior muscle group at lower leg level, right leg, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Quinu', 'Long labor, unspecified');
insert into compannia (companniaNombre, companniaDescrp) values ('Realpoint', 'Osteochondrodysplasia with defects of growth of tubular bones and spine');
insert into compannia (companniaNombre, companniaDescrp) values ('Twitterwire', 'Sprain of interphalangeal joint of left great toe, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Gabspot', 'Person on outside of bus injured in collision with pedal cycle in nontraffic accident, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Quatz', 'Corrosion of first degree of multiple right fingers (nail), not including thumb, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Gigazoom', 'Nondisplaced fracture of shaft of fourth metacarpal bone, right hand, sequela');
insert into compannia (companniaNombre, companniaDescrp) values ('Browsecat', 'Malignant neoplasm of small intestine');
insert into compannia (companniaNombre, companniaDescrp) values ('Rhynoodle', 'Nondisplaced comminuted fracture of shaft of radius, right arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into compannia (companniaNombre, companniaDescrp) values ('Skinix', 'Other injury of muscle(s) and tendon(s) of anterior muscle group at lower leg level, left leg');
insert into compannia (companniaNombre, companniaDescrp) values ('Gigabox', 'Benign neoplasm of unspecified ciliary body');
insert into compannia (companniaNombre, companniaDescrp) values ('Avamm', 'Occupant of powered streetcar injured in transport accident');
insert into compannia (companniaNombre, companniaDescrp) values ('Photobean', 'Displaced avulsion fracture of left ischium, initial encounter for closed fracture');
insert into compannia (companniaNombre, companniaDescrp) values ('Twitterbeat', 'Cerebral infarction due to embolism of unspecified anterior cerebral artery');
insert into compannia (companniaNombre, companniaDescrp) values ('Fanoodle', 'Displaced fracture of pisiform, right wrist, initial encounter for closed fracture');
insert into compannia (companniaNombre, companniaDescrp) values ('Devshare', 'Maternal care for unspecified type scar from previous cesarean delivery');
