-- DROP TABLE `actor`;
-- DROP TABLE `beneficio`;
-- DROP TABLE `cargoMontoSuscripcion`;
-- DROP TABLE `cargo`;
-- DROP TABLE `color`;
-- DROP TABLE `comGal`;
-- DROP TABLE `combate`;
-- DROP TABLE `compannia` ;
-- DROP TABLE `creador`;
-- DROP TABLE `cuentaGratis`;
-- DROP TABLE `cuentaMed` ;
-- DROP TABLE `cuenta` ;
-- DROP TABLE `descuento` ;
-- DROP TABLE `director`;
-- DROP TABLE `dispositivo` ;
-- DROP TABLE `galeria`;
-- DROP TABLE `heroeVillanoCivil`;
-- DROP TABLE `heroeVillanoEnfrentados` ;
-- DROP TABLE `historial` ;
-- DROP TABLE `lugar` ;
-- DROP TABLE `medComic` ;
-- DROP TABLE `medPais` ;
---- DROP TABLE `medPelGananc`;
-- DROP TABLE `medPelicula`;
-- DROP TABLE `medSerie`;
-- DROP TABLE `medVidPlatf`;
-- DROP TABLE `medVideojuego` ;
-- DROP TABLE `medio`;
-- DROP TABLE `miLista` ;
-- DROP TABLE `objeto`;
-- DROP TABLE `ocupacion`;
-- DROP TABLE `orgMed` ;
-- DROP TABLE `organizacion` ;
-- DROP TABLE `perCargOrg`;
-- DROP TABLE `perMed` ;
-- DROP TABLE `perfil` ;
-- DROP TABLE `persCivil`;
-- DROP TABLE `persCreador`;
-- DROP TABLE `persNacion`;
DROP TABLE `persObjeto` ;
DROP TABLE `persOcupacion` ;
DROP TABLE `persPoder` ;
DROP TABLE `persVillano`;
DROP TABLE `personaje`;
DROP TABLE `plataforma` ;
DROP TABLE `poder`;
DROP TABLE `rating ` ;
DROP TABLE `recomendacion` ;
DROP TABLE `sede` ;
DROP TABLE `tarjeta`;
DROP TABLE `tipoObjeto`;
DROP TABLE `trajeColor` ;
DROP TABLE `usuDisp`;
DROP TABLE `usuGal`;
DROP TABLE `usuTarj`; 
DROP TABLE `usuario`;